# Generated by Django 4.2.21 on 2025-06-11 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.TextField()),
                ('activity_type', models.CharField(choices=[('INFO', 'Info'), ('SUCCESS', 'Success'), ('ERROR', 'Error'), ('ALERT', 'Alert'), ('LOGIN', 'Login')], default='INFO', max_length=20)),
                ('metadata', models.JSONField(blank=True, help_text='Optional contextual data (loan_id, emi_id, etc.)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='triggered_activities', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequiredAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('LOAN', 'Loan'), ('EMI', 'EMI'), ('REPAYMENT', 'Repayment'), ('PAYMENT', 'Payment'), ('PROFILE', 'Profile Update'), ('KYC', 'KYC Verification'), ('FINANCIAL_DETAIL', 'Financial Detail')], max_length=20)),
                ('action_desc', models.TextField()),
                ('related_object_id', models.CharField(blank=True, help_text='Optional: ID of related object like loan, payment, etc.', max_length=100, null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Optional contextual data for UI or logic', null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_action_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['is_action_completed', 'due_date', '-created_at'],
            },
        ),
    ]
