# Generated by Django 4.2.21 on 2025-06-14 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_useractivity_requiredaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='purpose',
        ),
        migrations.AddField(
            model_name='transaction',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='failed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='initiated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Any extra data from Razorpay or app context', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_platform',
            field=models.CharField(blank=True, choices=[('RAZORPAY', 'Razorpay'), ('PHONEPE', 'PhonePe'), ('PAYTM', 'Paytm')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='reference_id',
            field=models.CharField(blank=True, help_text='For audit or external references', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('INITIATED', 'Initiated'), ('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='INITIATED', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('LOAN_PAYMENT', 'Loan Payment'), ('PAYOUT', 'Payout to Borrower'), ('REFUND', 'Refund to Lender'), ('EMI', 'EMI Payment'), ('REQUESTED_PAYMENT', 'Requested Payment')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('PARTIAL_APPROVED', 'Partial Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('DEFAULTED', 'Defaulted'), ('CLOSED_EARLY', 'Closed Early')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
